### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by royroev** [FormidableLabs/nuka-carousel#358]
When wrapAround={false} Error in console  - Cannot read property 'call' of undefined

**Comment by ryan-roemer** [comment]
We'll need a little more information here. Can you either:

- Open a PR with a failing regression test? or;
- Create a minimal repository with install + error reproduction steps so we can easily clone it and see the error in action?

Thanks!

**Comment by ryan-roemer** [comment]
Closing due to inactivity / lack of a reproduction.

**Comment by mic159** [comment]
This is happening all the time, its a very noisy error.

**Comment by ryan-roemer** [comment]
Thanks @mic159 -- bug is verified!

In `schedule.js` this code:

```js
  function tick(elapsed) {
    var t = 1;

    if (elapsed < transition.duration) {
      t = transition.ease.call(null, elapsed / transition.duration); // <== RIGHT HERE `transition.ease` is `undefined`
    } else {
      transition.timer.restart(stop);
      transition.state = ENDING;
    }
```

This corresponds to code in `react-move`: https://github.com/react-tools/react-move/blob/v2.7.0/src/core/transition/schedule.js#L121-L129 (picking `v2.7.0` here). Modern `react-move` looks significantly different (that file isn't even present).

`nuka-carousel` declares a dep at: https://github.com/FormidableLabs/nuka-carousel/blob/v4.4.7/package.json#L13 . Perhaps someone can experiment with upgrading `react-move` within semver `2.x.x` range and above it?  Or, maybe we can look if we need to pass some empty value _to_ `react-move` to avoid this in nuka?

... in any case, now we have some starting points to investigate! 🎉

**Comment by sarmeyer** [comment]
@mic159 `easeOutCirc` is not a valid `edgeEasing` value - check out https://github.com/d3/d3-ease for valid `edgeEasing` options. 

Also, after upgrading to v4.5.6, I no longer see this issue in your codesandbox.

**Comment by mic159** [comment]
@sarmeyer I updated the codesandbox to 4.5.6 and now it's getting the same error, but with a different name:

`Uncaught TypeError: transition.timing.ease is not a function`

**Comment by sarmeyer** [comment]
@mic159 `easeOutCirc` is not a valid `edgeEasing` value. Valid options are here  https://github.com/d3/d3-ease
